### ISSUE TITLE
Rebase Integration Strategy

### ISSUE THREAD

**Issue by bogdandit** [bogdandit/Workflows471Test#3]
References user story #1

## TODO:
- [ ] Create a new PR having the **base** branch `master` and the **compare** branch `task-3_rebase`
- [ ] Edit the description of the PR to reference this task
- [ ] Understand the commits and changes made to the PR
- [ ] In the PR, use the `Rebase and merge` option to integrate the changes into `master`
- [ ] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
