### ISSUE TITLE
Squash with Default Message Integration Strategy

### ISSUE THREAD

**Issue by bogdandit** [bogdandit/Workflows471Test#4]
References user story #1

## TODO:
- [ ] Create a new PR having the **base** branch `master` and the **compare** branch `task-4_squash`
- [ ] Edit the description of the PR to reference this task
- [ ] Understand the commits and changes made to the PR
- [ ] In the PR, use the `Squash and merge` option to integrate the changes into `master` and the commit message should be the default one provided by GitHub (e.g., `task-4_squash (#<ID_PR>)`)
- [ ] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
